version: "3.8"
services:
  nginx:
    build: "./containers/nginx"
    ports:
      - "80:80"
    container_name: "nginx"
    networks:
      - app
    depends_on:
      - node  

  node:
    build: "./containers/node"
    container_name: "triviastack"
    networks:
      - app
    environment:
      - HOST_REDIRECT


networks:
  app:
    driver: bridge
